[docs] Add auto generated docs
opensearch-project/terraform-provider-opensearch pull request #31
Opened 2023-03-27 01:25 UTC by phillbaker

### Description
_Describe what this change achieves._

Adds auto generated docs for all resources

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 
Closes https://github.com/opensearch-project/terraform-provider-opensearch/issues/8

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-03 23:49 UTC, bbarani commented
@prudhvigodithi @peterzhuamazon Can you please review and add your comments?

2023-04-04 04:10 UTC, prudhvigodithi requested changes

2023-04-04 04:10 UTC, prudhvigodithi commented on docs/index.md
> +# Configure the Elasticsearch provider
Hey @phillbaker this shows as `Elasticsearch provider`, is this what generated by generated by https://github.com/hashicorp/terraform-plugin-docs ?, can you please check how is this `Elasticsearch` being inferred.
Thank you

2023-04-04 04:10 UTC, prudhvigodithi commented on docs/index.md
> +provider "elasticsearch" {
Also I see lot of references with elasticsearch.

2023-04-04 04:13 UTC, prudhvigodithi commented on docs/index.md
> +resource "elasticsearch_index_template" "template_1" {
should be as [opensearch_index_template](https://github.com/opensearch-project/terraform-provider-opensearch/blob/main/provider/provider.go#L217)

2023-04-05 01:58 UTC, phillbaker commented
Updated, please take a look @prudhvigodithi

2023-04-06 16:52 UTC, prudhvigodithi commented
Thanks @phillbaker just a thought should we add the supported version of OpenSearch in the readme so that users can starting using with the supported version?
Thank you

2023-04-07 22:06 UTC, prudhvigodithi commented
Hey 

> Thanks @phillbaker just a thought should we add the supported version of OpenSearch in the readme so that users can starting using with the supported version?
> Thank you

@phillbaker I'm to start with this PR and update the readme later with the supported matrix versions.
Thank you

2023-04-07 22:07 UTC, prudhvigodithi commented
One More change is I can see the reference to `kibana` as well, can you please check @phillbaker

2023-04-10 16:14 UTC, prudhvigodithi commented
Hey @phillbaker can you please check my previous comments when you get a chance?
Thank you

2023-04-12 21:53 UTC, prudhvigodithi commented
Hey @phillbaker just in case if you are not aware about the [OpenSearch public slack](https://opensearch.org/slack.html), please feel free to join for better reach and discuss more about the terraform repo :) .
Thank you

2023-04-13 02:37 UTC, phillbaker commented
> should we add the supported version of OpenSearch in the readme

added

> I can see the reference to kibana

added

2023-04-13 03:33 UTC, prudhvigodithi approved these changes

2023-04-13 03:34 UTC, prudhvigodithi commented
Thanks @phillbaker, @peterzhuamazon @bbarani can you please add your review?
Thank you

2023-04-13 16:39 UTC, peterzhuamazon approved these changes

2023-04-13 16:40 UTC, merged